default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV.fetch('DB_USERNAME', 'root') %>
  host:     <%= ENV.fetch('DB_HOST', 'localhost') %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: rails_todo_development
  socket: <%= ENV.fetch('DB_SOCKET', '/tmp/mysql.sock') %>

test:
  <<: *default
  database: rails_todo_test
  
production:
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
